### ISSUE TITLE
'off' doesn't work

### ISSUE THREAD

**Issue by necolas** [npm-dom/delegate-dom#2]
Same problem as component/delegate. `on` wraps the callback in a function, so when `off` is passed the callback it doesn't match what was attached. You can see this if you modify the test body to:

``` js
  var fn = function (e) {
    t.ok(true);
  };

  on(document.body, 'ul li a', 'click', fn);
  document.querySelector('ul li a').click();
  on.off(document.body, 'click', fn);
  document.querySelector('ul li a').click();
```

The 2nd click will result in a count of `2` rather than the expected `1`.

I wrote this a while ago (needs a rewrite) – https://github.com/necolas/delegate.js/blob/master/delegate.js – to avoid this bug and remove the dependency on an "event" module…which is also broken / inadequate as it doesn't normalize the event object or account for IE-specific event names. IMO it's better to drop IE 8 (i.e., forget that dom-event module) and tell people to use a shim if they need, e.g., https://github.com/jonathantneal/EventListener/blob/master/EventListener.oldie.js.

**Comment by azer** [comment]
@necolas "on" shouldn't wrap the callback function: https://github.com/npm-dom/dom-event/blob/master/index.js#L6

**Comment by azer** [comment]
and if off doesn't work, test should fail: https://github.com/npm-dom/delegate-dom/blob/master/test.js#L12

**Comment by necolas** [comment]
it's being wrapped here - https://github.com/npm-dom/delegate-dom/blob/master/index.js#L27-L29

**Comment by necolas** [comment]
i think the reason the test passes is because you have `off` within `on`. `on` returns the _wrapped_ callback, so `fn` is correct when passed to the nested `off`. but when `off` isn't nested (i.e., not the `once` pattern), a consumer of the library passes the callback they've defined to `off` and it's not the same as the one that is registered by `on` (because it's wrapped in this library).

**Comment by azer** [comment]
you're right, btw it looks like we switched to http://npm.im/component-delegate module in the domquery package.

**Comment by necolas** [comment]
that also doesn't work, which is why i had to write https://github.com/necolas/delegate.js when building Twitter Cards
